# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-01 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180601_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': '20.用户'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '06.专题课或学位课模块'},
        ),
        migrations.AlterModelOptions(
            name='userauthtoken',
            options={'verbose_name_plural': '21.密钥Token'},
        ),
    ]
